### ISSUE TITLE
New release with python3 support

### ISSUE THREAD

**Issue by rlaverde** [mitsuhiko/python-inifile#7]
The lack of python 3 support is making [lektor-webpack-support](https://github.com/lektor/lektor-webpack-support) fail when trying to initialize

`lektor plugins add webpack-support`

python3 support has been added in #5, but It's after the last release (0.3)

In the meanwhile this can be fixed installing from github:
`pip install -U git+ssh://git@github.com/mitsuhiko/python-inifile.git`

**Comment by keikoro** [comment]
I just came here to say the same thing.

I tried to install a Lektor plugin (a different one), which failed due to the problem described in [Lektor issue #229](https://github.com/lektor/lektor/issues/229) (lack of Python 3 compatibility). While `initfile.py` got fixed sometime last year, an old version of the file is still being made available via PyPI, from where `python-initfile` is installed.

**Comment by timsueberkrueb** [comment]
Same here.

**Comment by mamoit** [comment]
I hate 👍 but in this case it is justified.
It really needs a release.
Can't use lektor plugins.

**Comment by keikoro** [comment]
I've meanwhile switched to Nikola and don't look back. ¯\\_(ツ)_/¯

**Comment by dwt** [comment]
Out of interest - is there a specific reason this library is not part of the pallets project?

**Comment by dwt** [comment]
Thanks for the release! (This issue can probably now be closed)
